development:
  english_study:
    class: LanguageStudyJob
    args: []
    schedule: every 5s
    queue: default
  stock_study:
    class: StockStudyJob
    args: []
    schedule: every 5s
    queue: default
