development:
  english_study:
    class: EnglishStudyJob
    args: []
    schedule: every 5s
    queue: default
  japanese_study:
    class: JapaneseStudyJob
    args: []
    schedule: every 5s
    queue: default
  stock_study:
    class: StockStudyJob
    args: []
    schedule: every 5s
    queue: default
